/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagesRouteImport } from './routes/_pages'
import { Route as PagesIndexRouteImport } from './routes/_pages/index'
import { Route as PagesMenuRouteImport } from './routes/_pages/menu'
import { Route as PagesContactRouteImport } from './routes/_pages/contact'

const PagesRoute = PagesRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesMenuRoute = PagesMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PagesRoute,
} as any)
const PagesContactRoute = PagesContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/contact': typeof PagesContactRoute
  '/menu': typeof PagesMenuRoute
  '/': typeof PagesIndexRoute
}
export interface FileRoutesByTo {
  '/contact': typeof PagesContactRoute
  '/menu': typeof PagesMenuRoute
  '/': typeof PagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pages': typeof PagesRouteWithChildren
  '/_pages/contact': typeof PagesContactRoute
  '/_pages/menu': typeof PagesMenuRoute
  '/_pages/': typeof PagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/contact' | '/menu' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/contact' | '/menu' | '/'
  id: '__root__' | '/_pages' | '/_pages/contact' | '/_pages/menu' | '/_pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PagesRoute: typeof PagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/': {
      id: '/_pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/menu': {
      id: '/_pages/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof PagesMenuRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/contact': {
      id: '/_pages/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PagesContactRouteImport
      parentRoute: typeof PagesRoute
    }
  }
}

interface PagesRouteChildren {
  PagesContactRoute: typeof PagesContactRoute
  PagesMenuRoute: typeof PagesMenuRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesContactRoute: PagesContactRoute,
  PagesMenuRoute: PagesMenuRoute,
  PagesIndexRoute: PagesIndexRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PagesRoute: PagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
